services:
  rm-xword:
    build: .
    container_name: rm-xword
    restart: unless-stopped
    volumes:
      - puzzles:/app/puzzles
      - ./nyt_cookies.txt:/app/nyt_cookies.txt:ro
      - ./rm_cookies.txt:/app/rm_cookies.txt
    env_file:
      - .env
    environment:
        # Set to "1" to run the job immediately on container start
        - RUN_NOW=1

volumes:
  puzzles:

